// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lddknaikooiwbkpagjuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZGtuYWlrb29pd2JrcGFnanVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDcxNTUsImV4cCI6MjA1OTg4MzE1NX0.fSTvsIZN2OqNDDPy5ruSV6UI98plifHEcVWaPdhG02k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);